select     
    WC_STR_STATS_F.YEAR_WID        YEAR,
                SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2)                 MONTH,
                W_BUSN_LOCATION_D.X_GLIN                   ENTITY,
                CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END        MARGIN_STATUS,
                'AC_ST9993044'                  ACCOUNT,
                SUM(WC_STR_STATS_F.CHG_MO_NMRTR_AMT)               AMOUNT,
                WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID        BUSINESS_GRP_WID
from      FBI_DW.WC_STR_STATS_F   WC_STR_STATS_F, FBI_DW.WC_QCR_ACT_CODE_D   WC_QCR_ACT_CODE_D, FBI_DW.WC_GBL_OPR_MONTHLY_F   WC_GBL_OPR_MONTHLY_F, FBI_DW.STG_ETL_BATCH_CTRL   STG_ETL_BATCH_CTRL, FBI_DW.WC_BUSINESS_GROUP_D   WC_BUSINESS_GROUP_D, FBI_DW.W_BUSN_LOCATION_RPNA_TREC_D   W_BUSN_LOCATION_D
where   (1=1)   
And (WC_STR_STATS_F.ACT_CODE_WID = WC_QCR_ACT_CODE_D.ROW_WID)
AND (WC_GBL_OPR_MONTHLY_F.BUSN_LOCATION_WID = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.BUSN_LOC_WID = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.PERIOD_WID = WC_GBL_OPR_MONTHLY_F.MCAL_PERIOD_WID)
AND (WC_GBL_OPR_MONTHLY_F.MONTH_WID = STG_ETL_BATCH_CTRL.MONTH_WID AND WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID  = STG_ETL_BATCH_CTRL.BUSINESS_GRP_WID)
AND (WC_BUSINESS_GROUP_D.ORG_NAME= STG_ETL_BATCH_CTRL.BUSINESS_GROUP)
And (WC_QCR_ACT_CODE_D.ACCOUNT_CODE = '215')
And (STG_ETL_BATCH_CTRL.IS_CURRENT = 'Y')
Group By WC_STR_STATS_F.YEAR_WID,
SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2),
W_BUSN_LOCATION_D.X_GLIN,
CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END,
WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID
UNION ALL
select     
                WC_STR_STATS_F.YEAR_WID        YEAR,
                SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2)                 MONTH,
                W_BUSN_LOCATION_D.X_GLIN                   ENTITY,
                CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END        MARGIN_STATUS,
                'AC_ST9993045'                  ACCOUNT,
                SUM(WC_STR_STATS_F.CHG_MO_DNMTR_AMT)              AMOUNT,
                WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID        BUSINESS_GRP_WID
from      FBI_DW.WC_STR_STATS_F   WC_STR_STATS_F, FBI_DW.WC_QCR_ACT_CODE_D   WC_QCR_ACT_CODE_D, FBI_DW.WC_GBL_OPR_MONTHLY_F   WC_GBL_OPR_MONTHLY_F, FBI_DW.W_BUSN_LOCATION_RPNA_TREC_D   W_BUSN_LOCATION_D, FBI_DW.STG_ETL_BATCH_CTRL   STG_ETL_BATCH_CTRL, FBI_DW.WC_BUSINESS_GROUP_D   WC_BUSINESS_GROUP_D
where   
                (1=1)     
                
And (WC_STR_STATS_F.ACT_CODE_WID      = WC_QCR_ACT_CODE_D.ROW_WID)
AND (WC_GBL_OPR_MONTHLY_F.BUSN_LOCATION_WID = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.BUSN_LOC_WID        = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.PERIOD_WID          = WC_GBL_OPR_MONTHLY_F.MCAL_PERIOD_WID)
AND (WC_GBL_OPR_MONTHLY_F.MONTH_WID  = STG_ETL_BATCH_CTRL.MONTH_WID AND WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID  = STG_ETL_BATCH_CTRL.BUSINESS_GRP_WID)
AND (WC_BUSINESS_GROUP_D.ORG_NAME= STG_ETL_BATCH_CTRL.BUSINESS_GROUP)
And (WC_QCR_ACT_CODE_D.ACCOUNT_CODE        = '215')
And (STG_ETL_BATCH_CTRL.IS_CURRENT = 'Y')

Group By WC_STR_STATS_F.YEAR_WID,
SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2),
W_BUSN_LOCATION_D.X_GLIN,
CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END,
WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID
UNION ALL
select     
                WC_STR_STATS_F.YEAR_WID        YEAR,
                SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2)                 MONTH,
                W_BUSN_LOCATION_D.X_GLIN                   ENTITY,
                CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END        MARGIN_STATUS,
                'AC_ST9993046'                  ACCOUNT,
                SUM(WC_STR_STATS_F.CHG_MO_NMRTR_AMT)               AMOUNT,
                WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID        BUSINESS_GRP_WID
from      FBI_DW.WC_STR_STATS_F   WC_STR_STATS_F, FBI_DW.WC_QCR_ACT_CODE_D   WC_QCR_ACT_CODE_D, FBI_DW.WC_GBL_OPR_MONTHLY_F   WC_GBL_OPR_MONTHLY_F, FBI_DW.W_BUSN_LOCATION_RPNA_TREC_D   W_BUSN_LOCATION_D, FBI_DW.WC_BUSINESS_GROUP_D   WC_BUSINESS_GROUP_D, FBI_DW.STG_ETL_BATCH_CTRL   STG_ETL_BATCH_CTRL
where (1=1)     
And (WC_STR_STATS_F.ACT_CODE_WID = WC_QCR_ACT_CODE_D.ROW_WID)
AND (WC_GBL_OPR_MONTHLY_F.BUSN_LOCATION_WID = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.BUSN_LOC_WID        = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.PERIOD_WID          = WC_GBL_OPR_MONTHLY_F.MCAL_PERIOD_WID)
AND (WC_GBL_OPR_MONTHLY_F.MONTH_WID  = STG_ETL_BATCH_CTRL.MONTH_WID AND WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID  = STG_ETL_BATCH_CTRL.BUSINESS_GRP_WID)
AND (WC_BUSINESS_GROUP_D.ORG_NAME= STG_ETL_BATCH_CTRL.BUSINESS_GROUP)
And (WC_QCR_ACT_CODE_D.ACCOUNT_CODE        = '205')
And (STG_ETL_BATCH_CTRL.IS_CURRENT = 'Y')
Group By WC_STR_STATS_F.YEAR_WID,
SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2),
W_BUSN_LOCATION_D.X_GLIN,
CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END,
WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID
UNION ALL
select     
                WC_STR_STATS_F.YEAR_WID        YEAR,
                SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2)                 MONTH,
                W_BUSN_LOCATION_D.X_GLIN                   ENTITY,
                CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END        MARGIN_STATUS,
                'AC_ST9993047'                  ACCOUNT,
                SUM(WC_STR_STATS_F.CHG_MO_DNMTR_AMT)              AMOUNT,
                WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID        BUSINESS_GRP_WID
from      FBI_DW.WC_STR_STATS_F   WC_STR_STATS_F, FBI_DW.WC_QCR_ACT_CODE_D   WC_QCR_ACT_CODE_D, FBI_DW.WC_GBL_OPR_MONTHLY_F   WC_GBL_OPR_MONTHLY_F, FBI_DW.WC_BUSINESS_GROUP_D   WC_BUSINESS_GROUP_D, FBI_DW.W_BUSN_LOCATION_RPNA_TREC_D   W_BUSN_LOCATION_D, FBI_DW.STG_ETL_BATCH_CTRL   STG_ETL_BATCH_CTRL
where (1=1)     
And (WC_STR_STATS_F.ACT_CODE_WID = WC_QCR_ACT_CODE_D.ROW_WID)
AND (WC_GBL_OPR_MONTHLY_F.BUSN_LOCATION_WID = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.BUSN_LOC_WID   = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.PERIOD_WID          = WC_GBL_OPR_MONTHLY_F.MCAL_PERIOD_WID)
AND (WC_GBL_OPR_MONTHLY_F.MONTH_WID  = STG_ETL_BATCH_CTRL.MONTH_WID AND WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID  = STG_ETL_BATCH_CTRL.BUSINESS_GRP_WID)
AND (WC_BUSINESS_GROUP_D.ORG_NAME= STG_ETL_BATCH_CTRL.BUSINESS_GROUP)
And (WC_QCR_ACT_CODE_D.ACCOUNT_CODE        = '205')
And (STG_ETL_BATCH_CTRL.IS_CURRENT = 'Y')
Group By WC_STR_STATS_F.YEAR_WID,
SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2),
W_BUSN_LOCATION_D.X_GLIN,
CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END,
WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID
UNION ALL
select     
                WC_STR_STATS_F.YEAR_WID        YEAR,
                SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2)                 MONTH,
                W_BUSN_LOCATION_D.X_GLIN                   ENTITY,
                CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END        MARGIN_STATUS,
                'AC_ST9993048'                  ACCOUNT,
                SUM(WC_STR_STATS_F.CHG_MO_NMRTR_AMT)               AMOUNT,
                WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID        BUSINESS_GRP_WID
from      FBI_DW.WC_STR_STATS_F   WC_STR_STATS_F, FBI_DW.WC_QCR_ACT_CODE_D   WC_QCR_ACT_CODE_D, FBI_DW.WC_GBL_OPR_MONTHLY_F   WC_GBL_OPR_MONTHLY_F, FBI_DW.W_BUSN_LOCATION_RPNA_TREC_D   W_BUSN_LOCATION_D, FBI_DW.STG_ETL_BATCH_CTRL   STG_ETL_BATCH_CTRL, FBI_DW.WC_BUSINESS_GROUP_D   WC_BUSINESS_GROUP_D
where   
                (1=1)     
                
And (WC_STR_STATS_F.ACT_CODE_WID = WC_QCR_ACT_CODE_D.ROW_WID)
AND (WC_GBL_OPR_MONTHLY_F.BUSN_LOCATION_WID = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.BUSN_LOC_WID        = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.PERIOD_WID          = WC_GBL_OPR_MONTHLY_F.MCAL_PERIOD_WID)
AND (WC_GBL_OPR_MONTHLY_F.MONTH_WID  = STG_ETL_BATCH_CTRL.MONTH_WID AND WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID  = STG_ETL_BATCH_CTRL.BUSINESS_GRP_WID)
AND (WC_BUSINESS_GROUP_D.ORG_NAME= STG_ETL_BATCH_CTRL.BUSINESS_GROUP)
And (WC_QCR_ACT_CODE_D.ACCOUNT_CODE        = '100')
And (WC_STR_STATS_F.QCR_VALID_FLAG     <> 'N')
And (STG_ETL_BATCH_CTRL.IS_CURRENT = 'Y')

Group By WC_STR_STATS_F.YEAR_WID,
SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2),
W_BUSN_LOCATION_D.X_GLIN,
CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END,
WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID
UNION ALL
select     
                WC_STR_STATS_F.YEAR_WID        YEAR,
                SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2)                 MONTH,
                W_BUSN_LOCATION_D.X_GLIN                   ENTITY,
                CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END        MARGIN_STATUS,
                'AC_ST9993049'                  ACCOUNT,
                SUM(WC_STR_STATS_F.CHG_MO_DNMTR_AMT)              AMOUNT,
                WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID        BUSINESS_GRP_WID
from      FBI_DW.WC_STR_STATS_F   WC_STR_STATS_F, FBI_DW.WC_QCR_ACT_CODE_D   WC_QCR_ACT_CODE_D, FBI_DW.WC_GBL_OPR_MONTHLY_F   WC_GBL_OPR_MONTHLY_F, FBI_DW.W_BUSN_LOCATION_RPNA_TREC_D   W_BUSN_LOCATION_D, FBI_DW.WC_BUSINESS_GROUP_D   WC_BUSINESS_GROUP_D, FBI_DW.STG_ETL_BATCH_CTRL   STG_ETL_BATCH_CTRL
where(1=1)                  
And (WC_STR_STATS_F.ACT_CODE_WID = WC_QCR_ACT_CODE_D.ROW_WID)
AND (WC_GBL_OPR_MONTHLY_F.BUSN_LOCATION_WID = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.BUSN_LOC_WID = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.PERIOD_WID          = WC_GBL_OPR_MONTHLY_F.MCAL_PERIOD_WID)
AND (WC_GBL_OPR_MONTHLY_F.MONTH_WID  = STG_ETL_BATCH_CTRL.MONTH_WID AND WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID  = STG_ETL_BATCH_CTRL.BUSINESS_GRP_WID)
AND (WC_BUSINESS_GROUP_D.ORG_NAME= STG_ETL_BATCH_CTRL.BUSINESS_GROUP)
And (WC_QCR_ACT_CODE_D.ACCOUNT_CODE        = '100')
And (WC_STR_STATS_F.QCR_VALID_FLAG     <> 'N')
And (STG_ETL_BATCH_CTRL.IS_CURRENT = 'Y')

Group By WC_STR_STATS_F.YEAR_WID,
SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2),
W_BUSN_LOCATION_D.X_GLIN,
CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END,
WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID
UNION ALL
select     WC_STR_STATS_F.YEAR_WID        YEAR,
                SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2)                 MONTH,
                W_BUSN_LOCATION_D.X_GLIN                   ENTITY,
                CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END        MARGIN_STATUS,
                'AC_ST9991264'                  ACCOUNT,
                SUM(WC_STR_STATS_F.CHG_MO_NMRTR_AMT)               AMOUNT,
                WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID        BUSINESS_GRP_WID
from      FBI_DW.WC_STR_STATS_F   WC_STR_STATS_F, FBI_DW.WC_QCR_ACT_CODE_D   WC_QCR_ACT_CODE_D, FBI_DW.WC_GBL_OPR_MONTHLY_F   WC_GBL_OPR_MONTHLY_F, FBI_DW.W_BUSN_LOCATION_RPNA_TREC_D   W_BUSN_LOCATION_D, FBI_DW.WC_BUSINESS_GROUP_D   WC_BUSINESS_GROUP_D, FBI_DW.STG_ETL_BATCH_CTRL   STG_ETL_BATCH_CTRL
where(1=1)      
And (WC_STR_STATS_F.ACT_CODE_WID = WC_QCR_ACT_CODE_D.ROW_WID)
AND (WC_GBL_OPR_MONTHLY_F.BUSN_LOCATION_WID = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.BUSN_LOC_WID        = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.PERIOD_WID          = WC_GBL_OPR_MONTHLY_F.MCAL_PERIOD_WID)
AND (WC_GBL_OPR_MONTHLY_F.MONTH_WID  = STG_ETL_BATCH_CTRL.MONTH_WID AND WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID  = STG_ETL_BATCH_CTRL.BUSINESS_GRP_WID)
AND (WC_BUSINESS_GROUP_D.ORG_NAME= STG_ETL_BATCH_CTRL.BUSINESS_GROUP)
And (WC_QCR_ACT_CODE_D.ACCOUNT_CODE  IN ('105', '110', '115', '120', '125', '130', '135'))
And (WC_STR_STATS_F.QCR_VALID_FLAG     <> 'N')
And (STG_ETL_BATCH_CTRL.IS_CURRENT = 'Y')
Group By WC_STR_STATS_F.YEAR_WID,
SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2),
W_BUSN_LOCATION_D.X_GLIN,
CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END,
WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID
UNION ALL
select     
                WC_STR_STATS_F.YEAR_WID        YEAR,
                SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2)                 MONTH,
                W_BUSN_LOCATION_D.X_GLIN                   ENTITY,
                CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END        MARGIN_STATUS,
                'AC_ST9991265'                  ACCOUNT,
                SUM(WC_STR_STATS_F.CHG_MO_NMRTR_AMT)               AMOUNT,
                WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID        BUSINESS_GRP_WID
from      FBI_DW.WC_STR_STATS_F   WC_STR_STATS_F, FBI_DW.WC_QCR_ACT_CODE_D   WC_QCR_ACT_CODE_D, FBI_DW.WC_GBL_OPR_MONTHLY_F   WC_GBL_OPR_MONTHLY_F, FBI_DW.W_BUSN_LOCATION_RPNA_TREC_D   W_BUSN_LOCATION_D, FBI_DW.STG_ETL_BATCH_CTRL   STG_ETL_BATCH_CTRL, FBI_DW.WC_BUSINESS_GROUP_D   WC_BUSINESS_GROUP_D
where                   (1=1)     
And (WC_STR_STATS_F.ACT_CODE_WID = WC_QCR_ACT_CODE_D.ROW_WID)
AND (WC_GBL_OPR_MONTHLY_F.BUSN_LOCATION_WID = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.BUSN_LOC_WID        = W_BUSN_LOCATION_D.ROW_WID)
AND (WC_STR_STATS_F.PERIOD_WID          = WC_GBL_OPR_MONTHLY_F.MCAL_PERIOD_WID)
AND (WC_GBL_OPR_MONTHLY_F.MONTH_WID  = STG_ETL_BATCH_CTRL.MONTH_WID AND WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID  = STG_ETL_BATCH_CTRL.BUSINESS_GRP_WID)
AND (WC_BUSINESS_GROUP_D.ORG_NAME= STG_ETL_BATCH_CTRL.BUSINESS_GROUP)
And (WC_QCR_ACT_CODE_D.ACCOUNT_CODE        = '200')
And (WC_STR_STATS_F.QCR_VALID_FLAG     <> 'N')
And (STG_ETL_BATCH_CTRL.IS_CURRENT = 'Y')
Group By WC_STR_STATS_F.YEAR_WID,
SUBSTR(TO_CHAR(WC_STR_STATS_F.PERIOD_WID),9,2),
W_BUSN_LOCATION_D.X_GLIN,
CASE
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_FULL_STORE_FLG = 'Y'
    THEN 'Comp Full'
    WHEN WC_GBL_OPR_MONTHLY_F.COMP_TEMP_STORE_FLG = 'Y'
    THEN 'Comp Temp'
    WHEN WC_GBL_OPR_MONTHLY_F.NEW_STORE_FLG = 'Y'
    THEN 'New Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.CLOSED_STORE_FLG = 'Y'
    THEN 'Closed Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.SOLD_STORE_FLG = 'Y'
    THEN 'Sold Restaurant'
    WHEN WC_GBL_OPR_MONTHLY_F.PURCHASED_STORE_FLG = 'Y'
    THEN 'Purchased Restaurant'
    ELSE 'NoMargin'
  END,
WC_GBL_OPR_MONTHLY_F.BUSINESS_GROUP_WID

