col "LOAD_PLAN_NAME" for a25;
set lines 2121 pagesize 2121 time on timing on;
alter session set nls_date_format = 'DD-MON-YYYY HH24:MI:SS';
Select LPI.I_LOAD_PLAN,LP.LOAD_PLAN_NAME,LPR.I_LP_INST ETL_PROC_WID, MIN(START_DATE) START_DT,LPR.STATUS,MAX(END_DATE)COMPLETION_DATE,SUM(DUration)/60 "DURATION(Minuts)"
from FBI_BIA_ODIREPO.SNP_LPI_RUN LPR,FBI_BIA_ODIREPO.SNP_LP_INST LPI,FBI_BIA_ODIREPO.SNP_LOAD_PLAN LP
where LPR.I_LP_INST =LPI.I_LP_INST
and LPI.I_LOAD_PLAN =LP.I_LOAD_PLAN
--and LPR.STATUS <>'R'
--and LPR.STATUS ='R'
and LP.LOAD_PLAN_NAME like 'GLODS_101_20160324_060336%'-- GLODS
and START_DATE > sysdate-2
group by LP.LOAD_PLAN_NAME,LPR.I_LP_INST,LPI.I_LOAD_PLAN,LPR.STATUS
order by 4 desc;
