alter session set nls_date_format = 'DD-MON-YYYY HH24:MI:SS';
set pages  100 lines 210
col SESS_NAME for a50
SELECT SESS_NO,
  SESS_NAME,
  SESS_BEG  START_TIME,
  SESS_END  END_TIME,
  round(SESS_DUR/60,2) MINUTES,
  SESS_STATUS,
  NB_ROW TOTAL_ROWS,
  NB_INS INSERT_COUNT,
  NB_UPD UPDATE_COUNT
FROM FBI_BIA_ODIREPO.SNP_SESSION
WHERE SESS_DUR<> 0
AND SESS_DUR  IS NOT NULL
AND SESS_STATUS='D'
AND SESS_NAME NOT LIKE 'EXEC%'
AND SESS_NAME in('&stepname')
and  SESS_BEG > sysdate -5
ORDER BY SESS_BEG,sess_name DESC;
